### ISSUE TITLE
Checklist for 5.1.0 (draft)

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/IsekaiMod#131]
## Implementations
- ~~Add Special power that that heals and also the effect of greater restoration without the material cost.~~
- ~~Add OP ability that applies the `UnitCondition.SpellcastingForbidden` condition.~~
- [x] Add Special power feature that implements `AddVendorDiscount`.
- [x] Add `Unreactable` Special Power.
- [x] Add `Excalibur` Special Power.
- [x] Add `Underpowered` OP abilities. These are less powerful ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=123322578))
- [x] Update description for `Extra Strike` (#156)
- [x] Rename `Auto Metamagic` to `Overpowered Ability — Auto Metamagic`
- [x] Change names of bonus features for base class (#145)
- [x] Change `Gifted` class feature description to say that they are multi-talented instead of being a genius.
- [x] Add Localization (#138)

## Pre-Release Tasks
- [x] Update LocalizationPack.json
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description

**Comment by ThePiggyGalaxy** [comment]
I saw that the base class currently doesn't have access to the bloodrager legacy, is this intended or not, because it's quite inconvenient. If intended please add a umm option or something allowing it for the base class

**Comment by JohN100x1** [comment]
the base class should have all legacies from what I remember, so if it does not then it is a bug.

**Comment by Nerin3** [comment]
Isn't it a bit weird that Mastermind loses this ability:
![image](https://user-images.githubusercontent.com/1911661/232620573-97e2af19-9383-42dc-8102-eefc51ea663a.png)

**Comment by JohN100x1** [comment]
Maybe I should change the description a bit and have it say that they are multi-talented instead.

**Comment by kjk001** [comment]
@JohN100x1 those legacies weren't actually missing by the way, the main purpose of splitting the secondary feat selection from the base isekai list was so that legacies could be set to not appear in the initial selection and only as a dual option at level 5.

That way the archetypes could also hold an advantage when it comes to the legacies and when they become available...

Did you re add them all or just the ones that you thought the base class should have?

I mean it is not a problem if the base class has immediate access to all but I kind of liked the idea that something like the Holy Beast Legacy was only selectable as Hero or God Emperor at start...

**Comment by JohN100x1** [comment]
My bad. It looks like I misunderstood the legacy selection sheet. I had added all the [legacies](https://github.com/JohN100x1/WOTR_IsekaiMod/commit/7bd0cd4375bf9fc47e06511eefdf58732083f8a8) to the base class.

**Comment by kjk001** [comment]
If you want that to be the state that is ok too.
I essentially thought the thing up as a three state system:
Primary Legacy 1 (available at level 1)
Secondary Legacy 0 (only available as second choice post level 5)
Forbidden Legacy -1 (never available)
and then tried to figure out a way to make that logic apply both to the archetypes and the class itself.

That way certain legacies give an extra boost to certain archetypes due to the early availability over the base class.
Someone that wants to be a two handed fighter would gravitate more to Edge Lord, or to Hero to be a shield specialist...

**Comment by Mythalar** [comment]
> Maybe I should change the description a bit and have it say that they are multi-talented instead.

Well was testing a bit a builds yesterday with nearly all subclasses and it would actually make sense to give "Gifted" ability to Mastermind : 

- It would be the only subclass with it,
- it would balance the loss of all bonus feats (that could be spent on various skill feats),
- it would balance the lack of any "major" aura.

As of now the Overlord can be nearly as good for spellcasting and quite more versatile.

Mastermind is the only (?) one to have access to arcanist exploits but, while quite usefull, the peak power is roughly +2 to caster level, or a greater bonus just twice a day ( Eldricht font abilities). It does not really compare with any major aura but with an advantage on D20 rolls it could be just nice.

**Comment by JohN100x1** [comment]
> Mastermind is the only (?) one to have access to arcanist exploits but, while quite usefull, the peak power is roughly +2 to caster level, or a greater bonus just twice a day ( Eldricht font abilities). It does not really compare with any major aura but with an advantage on D20 rolls it could be just nice.

I had originally wanted to add [new features](https://github.com/JohN100x1/WOTR_IsekaiMod/issues/100#issuecomment-1475358642) to replace the study target feature for villain (which led to the creation of mastermind), but it was discussed that [arcanist features should be added](https://github.com/JohN100x1/WOTR_IsekaiMod/issues/108#issuecomment-1478267358). Now that I've implemented the arcanist features, I don't feel inclined to rework it now.

I don't agree with your idea of giving "Gifted" feature to the mastermind. While I was reworking the classes, I saw that the base Isekai protagonist class had way less features than the subclasses which is why I add the "Gifted" feature and a few others (Hax, secret power, etc) in the first place for balance. Changing this would basically remove some incentive to play the base class.

**Comment by Mythalar** [comment]
> I had originally wanted to add [new features](https://github.com/JohN100x1/WOTR_IsekaiMod/issues/100#issuecomment-1475358642) to replace the study target feature for villain (which led to the creation of mastermind), but it was discussed that [arcanist features should be added](https://github.com/JohN100x1/WOTR_IsekaiMod/issues/108#issuecomment-1478267358). Now that I've implemented the arcanist features, I don't feel inclined to rework it now.

Oh I still think exploits give it a defining identities, was just throwing ideas.
I'v tested a build with sorcerer/witch/dark elementalist legacies thanks to part timer legacy and the options were endless!

I think in my runs I'll just add a +1 spell pen/lvl to my character and it will be a perfect caster without having to take all the boring spell feats line !

**Comment by Necht** [comment]
> * ~Add Special power that that heals and also the effect of greater restoration without the material cost.~
> * ~Add OP ability that applies the `UnitCondition.SpellcastingForbidden` condition.~

That sounds interesting. Why did you decide not to implement it?

**Comment by JohN100x1** [comment]
I would rather speed up the release of 5.1.0 than adding more features. They can always be added later.
