### ISSUE TITLE
Checklist for 5.2.0 (draft)

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/IsekaiMod#149]
## Implementations
- [ ] Add more dialogue (#146)
  - [ ] Finnean dialogue https://github.com/JohN100x1/IsekaiMod/issues/15#issuecomment-1515047241
  - [x] Irabeth dialogue https://github.com/JohN100x1/IsekaiMod/issues/146#issue-1679001777
- [x] Add `Master Summoner` OP ability https://github.com/JohN100x1/IsekaiMod/issues/2#issuecomment-1528295187
- [x] Add `None` option for `Hax` selection.
- [x] Add missing spells from update ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=124154241)).
- [x] Change UMM content settings to allow Isekai Dialogue without Isekai Protagonist Class ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=123962325)).
- [x] Change channel energy scaling with class level rather than character level. (#163)
- [x] Fixed Isekai dialogue showing up with Horgus when not Isekai Protagonist.
- [x] Fix typo for `Rationalist` background description.
- [x] Fix #160

## Pre-Release Tasks
- [ ] Update LocalizationPack.json
- [ ] Update CHANGELOG.md
- [ ] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description
