### ISSUE TITLE
Checklist for 5.3.0 (draft)

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/IsekaiMod#166]
## Implementations
- [x] Add shifter outfit in UMM appearance option.
- [x] Fix scaling of the minor forms for shifter legacy ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=124547985))
- ~~Investigate mod conflict with expanded elements and dark codex ([link](https://forums.nexusmods.com/index.php?/topic/12204503-isekai-mod/?p=124608300))~~
- [x] Add UMM option to adjust spells known table (#169)
- [x] Add UMM option to disable spellbooks from Isekai archetypes.

## Pre-Release Tasks
- [x] Update LocalizationPack.json
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description
