### ISSUE TITLE
Checklist for 5.4.0 (draft)

### ISSUE THREAD

**Issue by JohN100x1** [JohN100x1/IsekaiMod#185]
## Implementations
- [x] Excalibur and Magical Amplification change into а toggle ability. (#184)
- [x] max heal for hero (#184)
- [x] Fix `Killing Intent` (#184)
- [x] Rework `Supermassive` (#184)
- [x] Additional diaglogue (#146)
    - [x] Add additional dialogue option with statue in Nenio questline.
- ~~Add some polymorph abilities as special powers.~~
- [x] Fix number of challenges per day for cavalier legacies. 

## Pre-Release Tasks
- [x] Update LocalizationPack.json
- [x] Update CHANGELOG.md
- [x] Update README.md
- [x] Update Info.json
- [x] Update Repository.json

## Post-Release Tasks
- Update mod description
- Update mod version
- New screenshots
- Release description

**Comment by Necht** [comment]
Hi! I have a request for you.
Can you please add the polymorph abilities and dialogs in the next patch, and not in this one, in order to release it faster? I will also try to translate it as quickly as possible.
BG3 is coming out soon and I be very happy to play again the Pathfinder before that with your mod.

I understand that fashion development is a complicated matter, and I'm sincerely sorry that I'm rushing you. But I'm just afraid that I don't have time to play Pathfinder with your mod again before the release of BG3.

**Comment by JohN100x1** [comment]
Of course.
I've been more busy than usual, but I'll try to finish this update as soon as I can.
